apiVersion: batch/v1
kind: CronJob
metadata:
  name: chartmuseum-cronjob
spec:
  schedule: {{ .Values.cronjob.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob
            image: {{ .Values.cronjob.job.image }}
            command: {{ toYaml .Values.cronjob.job.command | nindent 16 }}
          restartPolicy: OnFailure
